SHORTEST_PATH_DIST = "shortDist"
SHORTEST_PATH_GAIN = "gainShort"
SHORTEST_PATH_DROP = "dropShort"
SHORTEST_PATH_ROUTE = "shortest_route"

ELEV_PATH_DIST = "elev_path_dist"
ELEV_PATH_GAIN = "elev_path_gain"
ELEV_PATH_DROP = "elev_path_drop"
ELEV_PATH_ROUTE = "elev_path_route"

ORIGIN = "start"
DESTINATION = "end"
FEATURE = "Feature"
LINESTRING = "LineString"
PROPERTIES = "properties"
GEOMETRY = "geometry"
TYPE = "type"
COORDINATES = "coordinates"
BOOL_POP = "bool_pop"